environment:
  matrix:
    # - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    #   APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYOR_JOB_NAME: "python37-x64-vs2017"
    # - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      # APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"

stack: python 3.7

init:
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install:  
  - |
     curl -LfsS -o faber.tar.gz https://github.com/stefanseefeld/faber/archive/release/0.2.tar.gz
     tar xf faber.tar.gz
     CD faber-release-0.2
     python setup.py install
     CD ..
  # report the available MSVC compilers
  - python -m faber.tools.msvc 
  - faber --with-boost-include=C:/Libraries/boost_1_69_0 target.arch=x64
  - python -m pip install cibuildwheel==2.1.1

build_script: python -m cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels