
name: Build RDKit platform wheels

# Build on every branch push, tag push, and pull request change:
on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
